server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3308/book_identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: marcus
    password: marcus@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 127.0.0.1:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  
## app config
app: 
  services:
    profile: http://localhost:8082/profile